export const featuredMentors = [
  {
    id: 1,
    name: "Sarah Johnson",
    title: "Senior Product Manager",
    company: "Google",
    image: "/placeholder.svg?height=80&width=80",
    rating: 4.9,
    sessions: 127,
    location: "San Francisco, CA",
    skills: ["Product Strategy", "Leadership", "Analytics"],
    price: 150,
    available: true,
  },
  {
    id: 2,
    name: "Michael Chen",
    title: "Senior Software Engineer",
    company: "Meta",
    image: "/placeholder.svg?height=80&width=80",
    rating: 4.8,
    sessions: 89,
    location: "Seattle, WA",
    skills: ["React", "System Design", "Architecture"],
    price: 120,
    available: false,
  },
  {
    id: 3,
    name: "Emily Rodriguez",
    title: "UX Design Lead",
    company: "Apple",
    image: "/placeholder.svg?height=80&width=80",
    rating: 4.9,
    sessions: 156,
    location: "Cupertino, CA",
    skills: ["UX Design", "Design Systems", "Research"],
    price: 180,
    available: true,
  },
  {
    id: 4,
    name: "David Kim",
    title: "Data Science Manager",
    company: "Netflix",
    image: "/placeholder.svg?height=80&width=80",
    rating: 4.7,
    sessions: 73,
    location: "Los Angeles, CA",
    skills: ["Data Science", "Machine Learning", "Python"],
    price: 140,
    available: true,
  },
]

export const testimonials = [
  {
    id: 1,
    name: "Alex Thompson",
    role: "Software Engineer",
    company: "Stripe",
    image: "/placeholder.svg?height=60&width=60",
    content:
      "The mentorship I received helped me transition from junior to senior engineer in just 8 months. The guidance was invaluable.",
    rating: 5,
  },
  {
    id: 2,
    name: "Maria Garcia",
    role: "Product Manager",
    company: "Airbnb",
    image: "/placeholder.svg?height=60&width=60",
    content:
      "My mentor helped me navigate complex product decisions and develop leadership skills. Highly recommend this platform!",
    rating: 5,
  },
  {
    id: 3,
    name: "James Wilson",
    role: "UX Designer",
    company: "Figma",
    image: "/placeholder.svg?height=60&width=60",
    content: "The design mentorship program transformed my approach to user research and helped me land my dream job.",
    rating: 5,
  },
]
